apiVersion: v1
kind: Service
metadata:
  name: mongo-storage
  namespace: nsd
  labels:
    name: mongo-storage
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-files-persistent-storage-claim
  namespace: nsd
spec:
  storageClassName: local-storage
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-files-persistent-storage
  namespace: nsd
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/conbex-mongo-files"
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-storage
  namespace: nsd
spec:
  serviceName: "mongo-storage"
  replicas: 1
  selector:
    matchLabels:
      role: mongo-storage
      environment: test
  template:
    metadata:
      labels:
        role: mongo-storage
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-files-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
      volumes:
        - name: mongo-files-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-files-persistent-storage-claim
